---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sausage-store
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.env.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.env.password | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.name }}-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sausage-store
data:
  POSTGRES_DB: {{ .Values.postgresql.env.database | quote }}
  PGDATA: {{ .Values.postgresql.env.pgData | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sausage-store
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgresql.containerPort }}
      targetPort: {{ .Values.postgresql.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.postgresql.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: sausage-store
spec:
  serviceName: {{ .Values.postgresql.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.name }}
    spec:
      containers:
        - name: {{ .Values.postgresql.name }}
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.postgresql.name }}-conf
            - secretRef:
                name: {{ .Values.postgresql.name }}-secret
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.containerPort }}
          resources:
{{ toYaml .Values.postgresql.resources | indent 12 }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgresql.env.user }}
                - -d
                - {{ .Values.postgresql.env.database }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          volumeMounts:
            - name: {{ .Values.postgresql.name }}-data
              mountPath: {{ .Values.postgresql.storage.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.postgresql.name }}-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size }}
