---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-{{ .Chart.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: "{{ .Chart.Name }}"
    app.kubernetes.io/part-of: sausage-store
data:
  SPRING_DATASOURCE_URL: {{ .Values.env.postgresUri | quote }}
  REPORT_PATH: {{ .Values.env.reportPath | quote }}
  LOG_PATH: {{ .Values.env.logPath | quote }}
