---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-{{ .Chart.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: "{{ .Chart.Name }}"
    app.kubernetes.io/part-of: sausage-store
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.postgresUser | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  SPRING_DATA_MONGODB_URI: {{ .Values.secrets.mongoUri | quote }}
